### ISSUE TITLE
How to authorize?

### ISSUE THREAD

**Issue by coczero** [David-Desmaisons/DiscogsClient#10]
All I want to do is search using the database api.
I don't want to authorize users or anything the like.
I got an consumer key and a consumer secret but all examples I find require an user to click "Authorize".
I just want to do a quit authorization with my own key and search the database.
How?

**Comment by David-Desmaisons** [comment]
You can create an application using your personal token using [token based authentication](https://github.com/David-Desmaisons/DiscogsClient/blob/master/README.md#token-based-authentication)

**Comment by coczero** [comment]
I tried that but:
1) I get no feedback if my authorization worked
2) I get empty results when searching so the authorization probably did not work.

**Comment by David-Desmaisons** [comment]
Check [Music.Cover.Finde](https://github.com/David-Desmaisons/Music.Cover.Finder/blob/master/Music.Cover.Finder/Model/Discogs/DiscogsClientProvider.cs) that uses token identification
