### ISSUE TITLE
Artist for each track in tracklist

### ISSUE THREAD

**Issue by MikeG06** [David-Desmaisons/DiscogsClient#2]
This package is working perfectly.
But some releases are compilations and each track has a different artist.
It would be nice to add an artist property in the "**DiscogsTrack**" class.

Thank you.

**Comment by David-Desmaisons** [comment]
Hi @MikeG06, do you have a JSON example of such data?

**Comment by MikeG06** [comment]
Hello,

Sorry I don't.
It's something I noticed when I was comparing data between **DiscogsClient** objects and the Web pages. I will try to get one as soon as I can.

Thank you for your support.

**Comment by David-Desmaisons** [comment]
Thanks, once you provide me the data I will update DiscogsClient

**Comment by MikeG06** [comment]
Hello,

When I get the following release ([696229](https://api.discogs.com/releases/696229)), I get the this JSON data. I've attached a file for you to look at it.

[DiscogsClientJSON.txt](https://github.com/David-Desmaisons/DiscogsClient/files/865604/DiscogsClientJSON.txt)

Thank you.

**Comment by David-Desmaisons** [comment]
Hi @MikeG06 , I just correct the issue. It will be included in next version of Discogs. Note that this version will contain breaking changes as asynchroneous API will be post-fixed by "Async"

**Comment by David-Desmaisons** [comment]
I just release version 2.0.0
