### ISSUE TITLE
Empty image url

### ISSUE THREAD

**Issue by horseyhorsey** [David-Desmaisons/DiscogsClient#3]
![noimage](https://user-images.githubusercontent.com/5377332/28086985-ccc928ce-6678-11e7-873b-b37794270539.jpg)

The client search is good for all other fields but I get empty urls on images? This release id was tested as well as your existing releaseId.

**Comment by David-Desmaisons** [comment]
Hello @horseyhorsey , I am not sure I understand the problem, Could you please share the corresponding search data? Did you check with som tools such as fiddle the data sent by discogs?

**Comment by horseyhorsey** [comment]
All data would come back in the search apart from the image urls. I think it's a problem my end on the authorization.

 I noticed a normal query has a 401 Unauth, but that's not obvious and didn't think to use fiddler, thanks for pointing that out.

**Comment by horseyhorsey** [comment]
Well...trying to track down my issue on database searches I finally noticed the _OAuthCompleteInformation was null in constructor! 

I'd been in there and added tokens but must have got sidetracked and never set it to the token. Sorry if I scared you, great job thanks.
