### ISSUE TITLE
Subtrack in tracklist

### ISSUE THREAD

**Issue by traponto** [David-Desmaisons/DiscogsClient#6]
Is there a way to get subtracks of an 'Index' track?
For example: in Pink Floyd Atom Heart Mother I have the track 'Atom Heart Mother' ('Index' track) with subtracks 1.a / 1.f

[Sample.zip](https://github.com/David-Desmaisons/DiscogsClient/files/1845556/Sample.zip)

**Comment by David-Desmaisons** [comment]
Is that information provided by dsicogs API?

**Comment by traponto** [comment]
referring to the example given above, seems that if the subtracks belong to a 'heading' type track they are extracted correctly. If instead they belong to an 'index' type track, these are not extracted. The release [r2678791] reports the first case and your client reports them correctly, the release [r11464584] reports the second case and in this case they are not extracted.

**Comment by traponto** [comment]
Here a json example where you can see a tracklist with 'index' track and the 'sub_tracks' that belong to it

[2106643_json.zip](https://github.com/David-Desmaisons/DiscogsClient/files/1848279/2106643_json.zip)

**Comment by David-Desmaisons** [comment]
What is the corresponding query/url?

**Comment by traponto** [comment]
https://api.discogs.com/releases/2106643

**Comment by David-Desmaisons** [comment]
Thanks, I will provide

**Comment by David-Desmaisons** [comment]
Corrected in version 2.1.0

**Comment by Elypsia** [comment]
Hello David;
Would you be interested in some custom dev work based on Discogs API ?
Kind regards,
Gregory Lacour
Elypsia Records




Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by traponto** [comment]
Sorry, I performed a test on last release and now I find the sub_track, but these could have in turn 'extraartists' that are not reported instead; attached a compressed file that includes what is returned from the Discogs site and what is present in your DiscogsRelease class. Furthermore, the 'Text' field may be present in 'Formats'.
Even if off-topic I try to ask if it is possible to make public a method that starting from url (and not from DiscogsImage) can extract the image present in the 'Thumb' field (now I extract it creating an instance of DiscogsImage)

**Comment by traponto** [comment]
[9093776_json.zip](https://github.com/David-Desmaisons/DiscogsClient/files/1863399/9093776_json.zip)

**Comment by David-Desmaisons** [comment]
1) extraartists => added in version 2.2.0

2) DiscogsImage => not currently in my plans

**Comment by traponto** [comment]
okay thanks
