### ISSUE TITLE
New info extracted from your library

### ISSUE THREAD

**Issue by traponto** [David-Desmaisons/DiscogsClient#8]
Hi, I wanted to ask if you were willing to integrate some information that I found in the DiscoGS DB and that are not currently extracted from your library.

For now I can not give you a precise list (in testing my applications sometimes I find something) but for now I could give you two / three that I found.

Thanks in advance,
   Traponto

**Comment by David-Desmaisons** [comment]
@traponto , yes I will maintain and improve this library.
Ideally what you can do is to provide the missing properties, their respective types, the corresponding documentation and an url example returning this kind of information.
PR are also very welcomed.

**Comment by traponto** [comment]
I
[alljson.zip](https://github.com/David-Desmaisons/DiscogsClient/files/2367316/alljson.zip)
n the Release structure I do not find the properties "series" and "artists_sort".

The first (series) should have the same structure related to "labels". An example can be found in file 2221110.json included in the attached compressed file.

The second (artists_sort) should be of string type and in every attached json file you can find an example, what I think is more significant is the one present in 3340518.json

From what I have seen these two properties are always present even if not used (in this case they are empty)

In the Format structure, I do not find the "text" property (string type). You can find two examples in the 9898418.json and 3041685.json files. In this case the property is not always present.

I hope I have provided the information clearly.

"PR are also very welcomed" ... what do you mean by PR?

**Comment by traponto** [comment]
if you mean this information:
https://api.discogs.com/releases/9898418
https://api.discogs.com/releases/3041685
https://api.discogs.com/releases/2221110
https://api.discogs.com/releases/3340518

then in the compressed file I sent you should find a .txt file that contains them

**Comment by traponto** [comment]
As a NuGet package I'm using DiscogsClient version 2.2.0. I see the update 2.2.1 is present but refers to adjustments made in June. Will you publish a new version?

**Comment by David-Desmaisons** [comment]
I just released version 2.3.0

**Comment by traponto** [comment]
I installed the update through NuGet, I see that other packages are updated and among these there is also System.Reactive 4.0.0, is that right? Now I have an error in the compilation phase at the instructions:

var observable = DiscogsClient.Search (discogsSearch);
await observable.ForEachAsync (OnResult);

[Upd_msg_and_err.zip](https://github.com/David-Desmaisons/DiscogsClient/files/2403221/Upd_msg_and_err.zip)

**Comment by David-Desmaisons** [comment]
You have to remove the references to all the Rx.XXX nuget packages that have been substitued by System.Reactive.

**Comment by traponto** [comment]
now the compilation is OK

Thanks
